mime ^video|audio, has mpv, X, flag f = mpv -- "$@"
mime ^video|audio, terminal, !X, has mpv = mpv -- "$@"
mime ^image/gif, has gifview, X, flag f = gifview -a "$@"

ext x?html?, has zen-browser, X, flag f = zen-browser -- "$@"
ext pdf, has zen-browser, X, flag f = zen-browser -- "$@"
ext pptx?|od[dfgpst]|docx?|sxc|xlsx?|xlt|xlw|gnm|gnumeric, has libreoffice, X, flag f = libreoffice "$@"
ext jpg|png, has imv, X, flag f = imv "$@"

label editor = nvim -- "$@"

