wallpaper {
    monitor = HDMI-A-1
    # path = $HOME/pictures/mountaingruvblur.png
    # path = $HOME/pictures/frieren.png
    path = $HOME/pictures/painting5.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    # path = $HOME/pictures/mountaingruvblur.png
    path = $HOME/pictures/frieren.png
    # path = $HOME/pictures/painting5.jpg
    fit_mode = cover
}
splash = false
ipc = true 
