### MONITORS ###
monitor = eDP-1, 2560x1600@60, 1920x0,1
monitor = HDMI-A-1, 1920x1080@120, 0x0,1

### MY PROGRAMS ###
$terminal = kitty
$menu = rofi -show drun

### AUTOSTART ###
# exec-once = nm-applet
exec-once = hyprpaper
exec-once = waybar
exec-once = hpr-scratcher
# exec-once = blueman-applet
exec-once = swaync

### ENVIRONMENT VARIABLES ###
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

### LOOK AND FEEL ###
source= ~/.config/hypr/configs/looknfeel.conf

### INPUT ###
source= ~/.config/hypr/configs/input.conf

### KEYBINDINGSS ###
source = ~/.config/hypr/configs/keybinds.conf

### WINDOW RULES ###
source = ~/.config/hypr/configs/windowrules.conf

###  NVIDIA  ###
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
cursor {
    no_hardware_cursors = true
}
