windowrule = match:class Godot, match:title Godot, tile on
windowrule = match:class Aseprite, float on, maximize on
windowrule = match:class Goxel, match:title Goxel, tile on
windowrule = match:class xdg-desktop-portal-gtk, float on
windowrule = match:class PureRef, float on, size 600 600, center on
